app:
  opml_path: "feed-rss-list.opml"
  day_limit: 8
  output_dir: "outputs"
  output_language: "zh" # zh for simplified Chinese, en for English

llm:
  endpoint_url: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
  model_id: "qwen-flash"
  auth_key: "sk-...." # Replace with your own auth key!!!
  timeout: 120

topics:
  Aging:
    positive_keywords:
      - aging
      - ageing
      - senescence
      - longevity
      - lifespan
      - age-related
    negative_keywords:
      - imaging
      - managing
      - packaging
      - staging
      - messaging
  Evolution:
    positive_keywords:
      - evolution
      - selection
      - evol
      - phylo
      - speciation
      - adaptation
    negative_keywords: []

email:
  enabled: true
  smtp_server: "smtp.qq.com" # If you use other email, please change smtp server address
  smtp_port: 465
  sender: "yourname@qq.com" # Replace with your account
  password: "......" # Replace with your email client password
  receivers:
    - "receiver1@aaa.com"
    - "receiver2@bbb.com"
    - "......" # Replace with exact receivers
  subject_prefix: "RSS AI Report"

